# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pyeKCm2axzM0BBhW8P_4odrxPjmMTb78
"""

import matplotlib.pyplot as plt
import numpy as np

def F(x):
  return x**3-x-1

def False_Pos(b,e):
  return (((e-b)*F(b))/(F(b)-F(e)) + b)

epsilon = 1e-8

temp1 = []
temp2 = []
temp3 = []
def bisection():
  b = -float(50)
  e = float(50)
  mid = (b+e)/2;
  itr = 1
  while( abs(F(mid)) > 1e-12):
    k = (b+e)/2
    if itr == 1:
      print("X1 = ",b,"X0 = ",e,"Mid = ",k,"F(mid) = ",F(mid),"AE = NULL","RAE = NULL")
    else:
      ae = abs(k-mid)
      rae = ae/k
      print("X1 = ",b,"X0 = ",e,"Mid = ",k,"F(mid) = ",F(mid),"AE = ",ae,"RAE = ",rae)
      temp1.append(itr)
      temp2.append(ae)
      temp3.append(rae)
    mid = k
    val = F(mid);
    if (val*F(b) > 0):
      b = mid
    else:
      e = mid
    itr = itr+1


temp4 = []
temp5 = []
temp6 = []
def FalsePosition():
  b = -float(50)
  e = float(50)
  mid = False_Pos(b,e)

  itr = 1
  while( abs(F(mid)) > 1e-3):
    k = False_Pos(b,e)
    if itr == 1:
      print("X1 = ",b,"X0 = ",e,"False Position Mid = ",k,"F(mid) = ",F(mid),"AE = NULL","RAE = NULL")
    else:
      ae = abs(k-mid)
      rae = ae/k
      print("X1 = ",b,"X0 = ",e,"False Position Mid = ",k,"F(mid) = ",F(mid),"AE = ",ae,"RAE = ",rae)
      temp4.append(itr)
      temp5.append(ae)
      temp6.append(rae)
    mid = k
    val = F(mid);
    if (val*F(b) > 0):
      b = mid
    else:
      e = mid
    itr = itr+1

bisection()
FalsePosition()

x = np.array(temp1)
y = np.array(temp2)
z = np.array(temp3)

plt.bar(x,y)
plt.xlabel("Iteration")
plt.ylabel("AE")
plt.show()
plt.bar(x,z)
plt.xlabel("Iteration")
plt.ylabel("RAE")
plt.show()


a = np.array(temp4)
b = np.array(temp5)
c = np.array(temp6)

plt.bar(a,b)
plt.xlabel("Iteration")
plt.ylabel("AE")
plt.show()
plt.bar(a,c)
plt.xlabel("Iteration")
plt.ylabel("RAE")
plt.show()

plt.plot(a,b)
plt.plot(x,y,'-.')

plt.xlabel("Iteration")
plt.ylabel("AE")

plt.show()

plt.plot(a,c,)
plt.plot(x,z,'-.')
plt.xlabel("Iteration")
plt.ylabel("RAE")

plt.show()