# -*- coding: utf-8 -*-
"""Lab8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dx7BWVdoxX-bFDp0MtJ03gtVhLHtnDYY
"""

import numpy as np
import matplotlib.pyplot as plt

def F(x):
  return x**2

def Rieman_Sum(temp1,temp2,tenmp3,temp4,temp5,temp6):
  iter = 4;
  while iter <= 4000:
    delx = float(4)/float(iter)

    x_left = float(0)
    x_right = float(delx)

    left_sum = float(0)
    right_sum = float(0)
    mid_sum = float(0)
    trapezoid_sum = float(0)


    while x_right <= 4:
      x_mid = (x_left+x_right)*0.5

      left_sum += F(x_left)*delx
      right_sum += F(x_right)*delx
      mid_sum += F(x_mid)*delx
      trapezoid_sum += 0.5*( F(x_left)+F(x_right) )*delx

      x_left += delx
      x_right += delx

    temp1.append(delx)
    temp2.append(left_sum)
    temp3.append(right_sum)
    temp4.append(mid_sum)
    temp5.append(trapezoid_sum)
    temp6.append(21.3333333333)
    iter += 1


temp1 = []
temp2 = []
temp3 = []
temp4 = []
temp5 = []
temp6 = []

Rieman_Sum(temp1,temp2,temp3,temp4,temp5,temp6)

a = np.array(temp1)
b = np.array(temp2)
c = np.array(temp3)
d = np.array(temp4)
e = np.array(temp5)
f = np.array(temp6)

plt.plot(a,b)
plt.plot(a,c)
plt.plot(a,d)
plt.plot(a,e)
plt.plot(a,f)


plt.xlabel("delX")
plt.ylabel("Sum")
plt.legend(["Left Sum","Right Sum","Mid Sum","Trapezoid Sum","Actual Sum"])
plt.show()